### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by wildskyf** [wi1d5ky/blog.wildsky.cc#15]
https://blog.wildsky.cc/feed.xml

**Comment by wi1d5ky** [comment]
放在 nav bar，未來要研究有沒有辦法用 email 訂閱。

**Comment by wi1d5ky** [comment]
active campaigner

**Comment by wildskyf** [comment]
https://tinyletter.com/

**Comment by wildskyf** [comment]
https://blog.wildsky.cc/index.xml
